### ISSUE TITLE
regarding BLE Fuzzing

### ISSUE THREAD

**Issue by NadSo** [yungtravla/airport#1]
Hello Yungtravla are conversation were locked, could we please get in touch? I am working on BLE Fuzzing and need some help.

**Comment by yungtravla** [comment]
Hi @NadSo

Here are some links that will help you

http://lmgtfy.com/?q=BLE+Fuzzing

https://github.com/evilsocket/bleah/issues/18

**Comment by yungtravla** [comment]
And please respect that this is an entirely different repo with no relevance to [bleah](https://github.com/evilsocket/bleah)
